services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
      - "8000:8000"  # Debug port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:surveys
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - SPRING_SQL_INIT_MODE=embedded
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - ./target/
        - action: rebuild
          path: pom.xml

  client:
    build:
      context: ./vue-surveys
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./vue-surveys
          target: /app
          ignore:
            - ./node_modules/
        - action: rebuild
          path: ./vue-surveys/package.json